/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation(libs.guava)
    testImplementation(libs.junit)

    implementation(libs.log4j.api)
    implementation(libs.log4j.core)

    implementation(libs.javafx.controls)
    implementation(libs.javafx.fxml) // если нужен FXML

    implementation(libs.sqlite.jdbc)
    implementation("ch.qos.logback:logback-classic:1.5.6")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

javafx {
    version = "23.0.2"
    modules("javafx.controls", "javafx.fxml")
}
